server:
  port: 8080
  servlet:
    context-path: /stdercorretora

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://ehajdewdtpolrf:7bae949e22dfebcdd91074f9c405cd47948d2c6d0aab38500e514d9f363b8fec@ec2-34-230-115-172.compute-1.amazonaws.com:5432/dcns4rpn425nt6
    username: ehajdewdtpolrf
    password: 7bae949e22dfebcdd91074f9c405cd47948d2c6d0aab38500e514d9f363b8fec
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
        ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO e Santander
