server:
  port: 8080
  servlet:
    context-path: /stdercorretora

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.17.0.2:5432/postgres
    username: postgres
    password: 123
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
        ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO e Santander